### ISSUE TITLE
[Adjust Player Camera] option doesn't affect "Nahobino-less" player character

### ISSUE THREAD

**Issue by giever** [Lyall/SMTVFix#26]
Not a big deal really, but I noticed that adjusting the player camera options doesn't seem to affect the camera when running around as the regular human player character (school uniform, short hair, etc.). Camera Angle in-game was set to Standard, and I did notice the changes I had set when running around Da'at as Nahobino, but not in the dorm or the research lab.

(For all I know, this may be intentional, which I would also understand as a choice.)

**Comment by Lyall** [comment]
Should be fixed in the next version. I was comparing the "standard angle" versus some fixed distance/fov/height values, but when you're in these other parts of the game the values are different. I've switched it up to use a native function to find out what FOV type you have set so it should work all the time.

**Comment by Lyall** [comment]
Fixed in v0.9.0
