### ISSUE TITLE
Video cutscenes lack borders in ultrawide

### ISSUE THREAD

**Issue by EspurrFan** [Lyall/SMTVFix#46]
Might be less of an issue but more of a suggestion, is there/would you add a way to enable black borders/pillarboxing during cutscenes when in ultrawide (in my case here, 21:9).

Example images here are during the intro cutscene and the second roughly about an hour into the game, where the world is loaded in behind the cutscene, causing distractions from the content on screen. This is my first playthrough of the game so I am also a bit cautious of potential spoilers from being transported to a new area, but either way it is a bit distracting and pillarboxing, or alternatively an option for pillarboxing would fix it.

Attached images below:
![image](https://github.com/user-attachments/assets/30dee76c-3c9e-41f9-b3d2-a8203cb6c20e)
![image](https://github.com/user-attachments/assets/7cb1b483-57ff-414a-8605-c10f46fef4df)

Thanks so much

**Comment by Lyall** [comment]
It's not possible as far as I know, as I explained in #30.

**Comment by Lyall** [comment]
Just re-opening this issue to say that this has been fixed/added in v0.9.3. Didn't think it was do-able at first but it turns out you _can_  add a completely black UI widget through pure C++.

Here is an example of the difference:
![ezgif-2-ccfb4fd3d4](https://github.com/user-attachments/assets/2a8c8d7e-03b4-4660-800e-d9a29869e1b4)

**Comment by EspurrFan** [comment]
Thank you!
